# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BgMQ0wM386W_fuaiYrmFFxcNIwI0ynaM
"""

# Install required library
!pip install cantera

# Imports
import numpy as np
import matplotlib.pyplot as plt
import cantera as ct

# --- Design Parameters ---
T0 = 288.2        # Ambient temperature, K
P0 = ct.one_atm    # Ambient pressure, Pa
V0 = 0             # Vehicle velocity, m/s
mdotair = 163.3       # kg/s, example
PRc = 6.4           # Compressor pressure ratio
Effc = 0.87        # Compressor efficiency
Effcomb = 0.98     # Combustor efficiency
dPcomb = 0.05      # Combustor pressure loss (fraction)
Efft = 0.91        # Turbine efficiency
dPjp = 0.03        # Jetpipe pressure loss (fraction)
#TIT=1600
# --- Initialize storage ---
F_map = []
TSFC_map = []

# --- Loop over Turbine Inlet Temperatures (TIT) ---
for TIT in np.linspace(1000, 2000, 21):
#for PRc in np.linspace(1.4, 11.4, 21):
#for mdotair in np.linespace(81.1,245.5,21)
    gas = ct.Solution('gri30.yaml')
    Yair = np.zeros(gas.n_species)
    Yair[gas.species_index('O2')] = 0.233
    Yair[gas.species_index('N2')] = 1 - 0.233

    # --- State 1: Compressor Inlet ---
    gas.TPY = T0, P0, Yair
    cp0 = gas.cp_mass
    gamma0 = gas.cp_mass / gas.cv_mass
    Tt1 = T0 + 0.5 * V0**2 / cp0
    Pt1 = P0 * (Tt1 / T0)**(gamma0 / (gamma0 - 1))

    # --- State 2: Compressor Exit ---
    gas.TPY = Tt1, Pt1, Yair
    cp1 = gas.cp_mass
    gamma1 = gas.cp_mass / gas.cv_mass
    Pt2 = PRc * Pt1
    Tt2s = Tt1 * PRc**((gamma1 - 1) / gamma1)
    Tt2 = Tt1 + (Tt2s - Tt1) / Effc
    wdotc = cp1 * (Tt2 - Tt1)

    # --- State 3: Combustor Exit ---
    Yfuel = np.zeros(gas.n_species)
    Yfuel[gas.species_index('CH4')] = 1
    Tt3 = Tt2
    AFR = 1000

    while Tt3 < TIT:
        AFR -= 1
        mdotfuel = mdotair / AFR
        gas.TPY = Tt2, Pt2, Yfuel + Yair * AFR
        gas.equilibrate('HP')
        Tt3s = gas.T
        Tt3 = Tt2 + Effcomb * (Tt3s - Tt2)

    Pt3 = gas.P * (1 - dPcomb)
    Yexh3 = gas.Y
    cp2 = gas.cp_mass
    qdotcomb = cp2 * (Tt3 - Tt2)

    # --- State 4: Turbine Exit ---
    gas.TPY = Tt3, Pt3, Yexh3
    cp3 = gas.cp_mass
    gamma3 = gas.cp_mass / gas.cv_mass
    Tt4 = Tt3 - AFR * wdotc / ((AFR + 1) * cp3)
    Tt4s = Tt3 - (Tt3 - Tt4) / Efft
    Pt4 = Pt3 * (Tt4s / Tt3)**(gamma3 / (gamma3 - 1))

    # --- State 5: Jetpipe Exit ---
    Tt5 = Tt4
    Pt5 = Pt4 * (1 - dPjp)

    # --- State 6: Nozzle Exit ---
    gas.TPY = Tt5, Pt5, Yexh3
    cp5 = gas.cp_mass
    gamma5 = gas.cp_mass / gas.cv_mass
    R5 = ct.gas_constant / gas.mean_molecular_weight
    PRcrit = ((gamma5 + 1) / 2)**(gamma5 / (gamma5 - 1))

    if Pt5 / P0 < PRcrit:
        # Not choked
        P6 = P0
        T6 = Tt5 * (P6 / Pt5)**((gamma5 - 1) / gamma5)
        V6 = np.sqrt(2 * cp5 * (Tt5 - T6))
        A6 = (mdotfuel + mdotair) * R5 * T6 / (P6 * V6)
    else:
        # Choked flow
        P6 = Pt5 / PRcrit
        T6 = Tt5 * (P6 / Pt5)**((gamma5 - 1) / gamma5)
        V6 = np.sqrt(2 * cp5 * (Tt5 - T6))
        A6 = (mdotfuel + mdotair) * R5 * T6 / (P6 * V6)

    # --- Performance ---
    F = ((mdotair + mdotfuel) * V6 - mdotair * V0 + A6 * (P6 - P0)) / 1e3  # Thrust [kN]
    TSFC = mdotfuel / F * 1e3  # [g/s/kN]

    if np.isnan(F):
        print("Engine not feasible for TIT =", TIT)
    else:
        print(f"TIT = {TIT:.0f} K → Thrust = {F:.2f} kN, TSFC = {TSFC:.2f} g/s/kN")

    F_map.append(F)
    TSFC_map.append(TSFC)

# --- Plot results ---
plt.figure(figsize=(5,4))
plt.plot(np.linspace(1000,2000,21), F_map, 'o-k')
#plt.plot(np.linspace(1.4, 11.4, 21), F_map, 'o-k')
#plt.plot(np.linspace(81.1, 245.5, 21), F_map, 'o-k')
plt.xlabel('TIT [K]')
#plt.xlabel('PRc[No Unit]')
#plt.xlabel('Airflow [kg/s]')
plt.ylabel('Thrust [kN]')
plt.title('Turbojet Thrust vs TIT')
#plt.title('Turbojet Thrust vs PRc')
#plt.title('Turbojet Thrust vs Airflow')
plt.grid(True)
plt.show()

plt.figure(figsize=(5,4))
plt.plot(np.linspace(1000,2000,21), TSFC_map, 'o-k')
#plt.plot(np.linspace(1.4, 11.4, 21), TSFC_map, 'o-k')
#plt.plot(np.linspace(81.1, 245.5, 21), F_map, 'o-k')
plt.xlabel('TIT [K]')
#plt.xlabel('PRc[No Unit]')
#plt.xlabel('Airflow [kg/s]')
plt.ylabel('TSFC [g/s/kN]')
plt.title('TSFC vs TIT')
#plt.title('TSFC vs PRc')
#plt.title('TSFC vs Airflow')
plt.grid(True)
plt.show()

